spectaql:
  displayAllServers: true
  targetDir: docs/gql

introspection:
  removeTrailingPeriodFromDescriptions: false
  schemaFile: ./generated/schema.graphql
  queryNameStrategy: capitalizeFirst
  fieldExpansionDepth: 2

  spectaqlDirective:
    enable: true

extensions:
  graphqlScalarExamples: true

info:
  title: Pynea Core API

servers:
  - url: https://localhost:3080/graphql
    description: Local